services:
  app:
    build:
      context: ../..
      dockerfile: envs/app-run/Dockerfile
    image: jb2:latest
    container_name: jb2
    restart: unless-stopped
    network_mode: host
    
    environment:
      # База данных PostgreSQL
      MAIN_DATASOURCE_URL: jdbc:postgresql://localhost:5437/postgres
      MAIN_DATASOURCE_USERNAME: root
      MAIN_DATASOURCE_PASSWORD: root
      
      # Temporal Workflow Server
      SPRING_TEMPORAL_CONNECTION_TARGET: localhost:7234
      
      # OpenAI API
      SPRING_AI_OPENAI_BASE_URL: http://localhost:4000
      # SPRING_AI_OPENAI_API_KEY: your-key-here
      
      # Профиль Spring
      SPRING_PROFILES_ACTIVE: dev
      
      # JVM настройки для слабого сервера
      # Ограничиваем до 1GB максимум (оставляем ~900MB системе и БД)
      JAVA_OPTS: -Xmx1024m -Xms256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=256m
      
      # Логирование (минимальное для экономии ресурсов)
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_IO_JMIX: INFO
      LOGGING_LEVEL_ECLIPSELINK_LOGGING_SQL: warn
      
      # Отключаем лишние фичи Spring для экономии памяти
      SPRING_JMX_ENABLED: "false"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      
      # Таймзона
      TZ: Europe/Moscow
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"    # Максимум 5MB на файл
        max-file: "2"     # Только 2 файла
        compress: "true"  # Сжимаем старые логи