version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.77.3-stable
    container_name: litellm_proxy
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    env_file:
      - .env
    command: --config /app/config.yaml --detailed_debug
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - litellm_network

  redis:
    image: redis:7-alpine
    container_name: litellm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - litellm_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    container_name: litellm_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - litellm_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  litellm_network:
    driver: bridge